# Visualization

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_can = pd.read_excel('canada.xlsx',sheet_name='Canada by Citizenship',skiprows=range(20),skipfooter=2)

In [ ]:
df_can.head()

,Immigrants,Foreigners,Belize,904,Latin America and the Caribbean,916,Central America,902,Developing regions,16,...,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1
0,Immigrants,Foreigners,Benin,903,Africa,914,Western Africa,902,Developing regions,2,...,112,95,116,183,205,238,290,284,391,397
1,Immigrants,Foreigners,Bhutan,935,Asia,5501,Southern Asia,902,Developing regions,0,...,1,5,10,7,36,865,1464,1879,1075,487
2,Immigrants,Foreigners,Bolivia (Plurinational State of),904,Latin America and the Caribbean,931,South America,902,Developing regions,44,...,85,134,139,107,143,214,180,86,83,107
3,Immigrants,Foreigners,Bosnia and Herzegovina,908,Europe,925,Southern Europe,901,Developed regions,0,...,188,211,217,209,182,156,168,140,121,119
4,Immigrants,Foreigners,Botswana,903,Africa,913,Southern Africa,902,Developing regions,10,...,9,7,11,8,28,15,42,53,64,76

In [ ]:
df_can.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 43 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Immigrants                       176 non-null    object
 1   Foreigners                       176 non-null    object
 2   Belize                           176 non-null    object
 3   904                              176 non-null    int64
 4   Latin America and the Caribbean  176 non-null    object
 5   916                              176 non-null    int64
 6   Central America                  176 non-null    object
 7   902                              176 non-null    int64
 8   Developing regions               176 non-null    object
 9   16                               176 non-null    int64
 10  27                               176 non-null    int64
 11  13                               176 non-null    int64
 12  21                               176 non-null    int64
 13  37                               176 non-null    int64
 14  26                               176 non-null    int64
 15  25                               176 non-null    int64
 16  23                               176 non-null    int64
 17  53                               176 non-null    int64
 18  33                               176 non-null    int64
 19  38                               176 non-null    int64
 20  41                               176 non-null    int64
 21  27.1                             176 non-null    int64
 22  37.1                             176 non-null    int64
 23  41.1                             176 non-null    int64
 24  43                               176 non-null    int64
 25  27.2                             176 non-null    int64
 26  33.1                             176 non-null    int64
 27  20                               176 non-null    int64
 28  37.2                             176 non-null    int64
 29  28                               176 non-null    int64
 30  24                               176 non-null    int64
 31  35                               176 non-null    int64
 32  16.1                             176 non-null    int64
 33  25.1                             176 non-null    int64
 34  37.3                             176 non-null    int64
 35  24.1                             176 non-null    int64
 36  28.1                             176 non-null    int64
 37  48                               176 non-null    int64
 38  38.1                             176 non-null    int64
 39  39                               176 non-null    int64
 40  36                               176 non-null    int64
 41  34                               176 non-null    int64
 42  53.1                             176 non-null    int64
dtypes: int64(37), object(6)
memory usage: 59.2+ KB

In [ ]:
df_can.columns

Index([                     'Immigrants',                      'Foreigners',
                                'Belize',                               904,
       'Latin America and the Caribbean',                               916,
                       'Central America',                               902,
                    'Developing regions',                                16,
                                      27,                                13,
                                      21,                                37,
                                      26,                                25,
                                      23,                                53,
                                      33,                                38,
                                      41,                            '27.1',
                                  '37.1',                            '41.1',
                                      43,                            '27.2',
                                  '33.1',                                20,
                                  '37.2',                                28,
                                      24,                                35,
                                  '16.1',                            '25.1',
                                  '37.3',                            '24.1',
                                  '28.1',                                48,
                                  '38.1',                                39,
                                      36,                                34,
                                  '53.1'],
      dtype='object')

In [ ]:
df_can.columns.values

array(['Immigrants', 'Foreigners', 'Belize', 904,
       'Latin America and the Caribbean', 916, 'Central America', 902,
       'Developing regions', 16, 27, 13, 21, 37, 26, 25, 23, 53, 33, 38,
       41, '27.1', '37.1', '41.1', 43, '27.2', '33.1', 20, '37.2', 28, 24,
       35, '16.1', '25.1', '37.3', '24.1', '28.1', 48, '38.1', 39, 36, 34,
       '53.1'], dtype=object)

In [ ]:
df_can.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175])

In [ ]:
# shape of table
df_can.shape

(176, 43)

In [ ]:
df_can.head()

,Immigrants,Foreigners,Belize,904,Latin America and the Caribbean,916,Central America,902,Developing regions,16,...,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1
0,Immigrants,Foreigners,Benin,903,Africa,914,Western Africa,902,Developing regions,2,...,112,95,116,183,205,238,290,284,391,397
1,Immigrants,Foreigners,Bhutan,935,Asia,5501,Southern Asia,902,Developing regions,0,...,1,5,10,7,36,865,1464,1879,1075,487
2,Immigrants,Foreigners,Bolivia (Plurinational State of),904,Latin America and the Caribbean,931,South America,902,Developing regions,44,...,85,134,139,107,143,214,180,86,83,107
3,Immigrants,Foreigners,Bosnia and Herzegovina,908,Europe,925,Southern Europe,901,Developed regions,0,...,188,211,217,209,182,156,168,140,121,119
4,Immigrants,Foreigners,Botswana,903,Africa,913,Southern Africa,902,Developing regions,10,...,9,7,11,8,28,15,42,53,64,76

In [ ]:
df_can.drop([904,916,902,'Immigrants','Foreigners'],axis=1,inplace=True)
df_can.head()

,Belize,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,...,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1
0,Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,...,112,95,116,183,205,238,290,284,391,397
1,Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,...,1,5,10,7,36,865,1464,1879,1075,487
2,Bolivia (Plurinational State of),Latin America and the Caribbean,South America,Developing regions,44,52,42,49,38,44,...,85,134,139,107,143,214,180,86,83,107
3,Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,188,211,217,209,182,156,168,140,121,119
4,Botswana,Africa,Southern Africa,Developing regions,10,1,3,3,7,4,...,9,7,11,8,28,15,42,53,64,76

In [ ]:
df_can.head(5)

,Belize,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,...,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1
0,Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,...,112,95,116,183,205,238,290,284,391,397
1,Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,...,1,5,10,7,36,865,1464,1879,1075,487
2,Bolivia (Plurinational State of),Latin America and the Caribbean,South America,Developing regions,44,52,42,49,38,44,...,85,134,139,107,143,214,180,86,83,107
3,Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,188,211,217,209,182,156,168,140,121,119
4,Botswana,Africa,Southern Africa,Developing regions,10,1,3,3,7,4,...,9,7,11,8,28,15,42,53,64,76

In [ ]:
df_can.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Belize                           176 non-null    object
 1   Latin America and the Caribbean  176 non-null    object
 2   Central America                  176 non-null    object
 3   Developing regions               176 non-null    object
 4   16                               176 non-null    int64
 5   27                               176 non-null    int64
 6   13                               176 non-null    int64
 7   21                               176 non-null    int64
 8   37                               176 non-null    int64
 9   26                               176 non-null    int64
 10  25                               176 non-null    int64
 11  23                               176 non-null    int64
 12  53                               176 non-null    int64
 13  33                               176 non-null    int64
 14  38                               176 non-null    int64
 15  41                               176 non-null    int64
 16  27.1                             176 non-null    int64
 17  37.1                             176 non-null    int64
 18  41.1                             176 non-null    int64
 19  43                               176 non-null    int64
 20  27.2                             176 non-null    int64
 21  33.1                             176 non-null    int64
 22  20                               176 non-null    int64
 23  37.2                             176 non-null    int64
 24  28                               176 non-null    int64
 25  24                               176 non-null    int64
 26  35                               176 non-null    int64
 27  16.1                             176 non-null    int64
 28  25.1                             176 non-null    int64
 29  37.3                             176 non-null    int64
 30  24.1                             176 non-null    int64
 31  28.1                             176 non-null    int64
 32  48                               176 non-null    int64
 33  38.1                             176 non-null    int64
 34  39                               176 non-null    int64
 35  36                               176 non-null    int64
 36  34                               176 non-null    int64
 37  53.1                             176 non-null    int64
dtypes: int64(34), object(4)
memory usage: 52.4+ KB

# format rename kolom :

## df_can.rename(columns={'namakolom':'namabaru','namakolom2':'namabaru',dst})

In [ ]:
# rename odName menjadi Country, areaName menjadi Continent, RegName menjadi Region
df_can.rename(columns={'OdName':'Country','AreaName':'Continent','RegName':'Region'},inplace=True)
df_can.head()

,Belize,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,...,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1
0,Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,...,112,95,116,183,205,238,290,284,391,397
1,Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,...,1,5,10,7,36,865,1464,1879,1075,487
2,Bolivia (Plurinational State of),Latin America and the Caribbean,South America,Developing regions,44,52,42,49,38,44,...,85,134,139,107,143,214,180,86,83,107
3,Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,188,211,217,209,182,156,168,140,121,119
4,Botswana,Africa,Southern Africa,Developing regions,10,1,3,3,7,4,...,9,7,11,8,28,15,42,53,64,76

In [ ]:
df_can.columns

Index([                         'Belize', 'Latin America and the Caribbean',
                       'Central America',              'Developing regions',
                                      16,                                27,
                                      13,                                21,
                                      37,                                26,
                                      25,                                23,
                                      53,                                33,
                                      38,                                41,
                                  '27.1',                            '37.1',
                                  '41.1',                                43,
                                  '27.2',                            '33.1',
                                      20,                            '37.2',
                                      28,                                24,
                                      35,                            '16.1',
                                  '25.1',                            '37.3',
                                  '24.1',                            '28.1',
                                      48,                            '38.1',
                                      39,                                36,
                                      34,                            '53.1'],
      dtype='object')

In [ ]:
df_can.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Belize                           176 non-null    object
 1   Latin America and the Caribbean  176 non-null    object
 2   Central America                  176 non-null    object
 3   Developing regions               176 non-null    object
 4   16                               176 non-null    int64
 5   27                               176 non-null    int64
 6   13                               176 non-null    int64
 7   21                               176 non-null    int64
 8   37                               176 non-null    int64
 9   26                               176 non-null    int64
 10  25                               176 non-null    int64
 11  23                               176 non-null    int64
 12  53                               176 non-null    int64
 13  33                               176 non-null    int64
 14  38                               176 non-null    int64
 15  41                               176 non-null    int64
 16  27.1                             176 non-null    int64
 17  37.1                             176 non-null    int64
 18  41.1                             176 non-null    int64
 19  43                               176 non-null    int64
 20  27.2                             176 non-null    int64
 21  33.1                             176 non-null    int64
 22  20                               176 non-null    int64
 23  37.2                             176 non-null    int64
 24  28                               176 non-null    int64
 25  24                               176 non-null    int64
 26  35                               176 non-null    int64
 27  16.1                             176 non-null    int64
 28  25.1                             176 non-null    int64
 29  37.3                             176 non-null    int64
 30  24.1                             176 non-null    int64
 31  28.1                             176 non-null    int64
 32  48                               176 non-null    int64
 33  38.1                             176 non-null    int64
 34  39                               176 non-null    int64
 35  36                               176 non-null    int64
 36  34                               176 non-null    int64
 37  53.1                             176 non-null    int64
dtypes: int64(34), object(4)
memory usage: 52.4+ KB

In [ ]:
pd.set_option('display.max_columns',None)
df_can.head()

,Belize,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1
0,Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205,238,290,284,391,397
1,Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487
2,Bolivia (Plurinational State of),Latin America and the Caribbean,South America,Developing regions,44,52,42,49,38,44,79,165,63,68,71,214,247,180,75,61,96,43,33,42,33,72,57,59,85,134,139,107,143,214,180,86,83,107
3,Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,0,0,0,0,0,0,258,2095,2090,3007,2599,2214,2789,2737,854,801,433,267,188,211,217,209,182,156,168,140,121,119
4,Botswana,Africa,Southern Africa,Developing regions,10,1,3,3,7,4,2,3,8,8,2,2,4,4,0,2,3,2,0,2,3,2,4,4,9,7,11,8,28,15,42,53,64,76

In [ ]:
df_can.sum(axis=1)
df_can['Total'] = df_can.sum(axis=1)
df_can.head()

<ipython-input-26-e1de89199917>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_can.sum(axis=1)
<ipython-input-26-e1de89199917>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_can['Total'] = df_can.sum(axis=1)

,Belize,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1,Total
0,Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205,238,290,284,391,397,2852
1,Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487,5876
2,Bolivia (Plurinational State of),Latin America and the Caribbean,South America,Developing regions,44,52,42,49,38,44,79,165,63,68,71,214,247,180,75,61,96,43,33,42,33,72,57,59,85,134,139,107,143,214,180,86,83,107,3205
3,Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,0,0,0,0,0,0,258,2095,2090,3007,2599,2214,2789,2737,854,801,433,267,188,211,217,209,182,156,168,140,121,119,21855
4,Botswana,Africa,Southern Africa,Developing regions,10,1,3,3,7,4,2,3,8,8,2,2,4,4,0,2,3,2,0,2,3,2,4,4,9,7,11,8,28,15,42,53,64,76,396

In [ ]:
# statistik deskriptif (mean,max,min,median,stdev,dll)
# describe automatically data integer/float
df_can.describe()

,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1,Total
count,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000,176.000000
mean,549.585227,614.193182,578.909091,421.005682,408.812500,387.750000,475.437500,746.852273,773.000000,911.931818,1043.914773,1146.482955,1223.892045,1229.380682,1073.289773,1028.278409,1083.659091,1037.630682,860.102273,964.176136,1153.948864,1288.647727,1186.977273,1157.022727,1232.880682,1368.085227,1312.403409,1245.017045,1308.323864,1338.897727,1489.119318,1328.903409,1384.778409,1387.039773,34740.329545
std,2047.322671,2260.433652,1959.523529,1262.927965,1256.917419,1131.955625,1284.589249,2212.274150,2564.889888,2679.508116,3314.441138,3093.810847,3491.410552,3666.166059,3793.839970,3242.771003,3480.874446,3214.636318,2497.347144,3025.518231,3837.906418,4145.555216,3832.345469,3796.750683,3887.349740,4637.747720,4105.914762,3604.403205,3868.178212,4005.908010,4670.471295,4221.467419,4452.488241,4437.956650,96171.646535
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.750000,0.000000,1.000000,1.000000,2.000000,3.000000,5.000000,10.250000,8.750000,9.000000,9.750000,13.500000,14.750000,14.750000,15.750000,22.000000,19.250000,21.750000,20.000000,28.750000,25.500000,33.500000,28.000000,26.750000,42.750000,37.500000,40.500000,44.500000,947.750000
50%,13.000000,10.000000,11.000000,11.500000,11.500000,16.500000,16.000000,29.500000,32.500000,44.500000,38.000000,56.500000,78.000000,88.500000,77.000000,95.500000,120.000000,106.000000,105.000000,119.000000,142.500000,176.000000,164.500000,158.000000,191.000000,201.500000,223.500000,196.500000,210.000000,215.500000,213.500000,187.500000,234.000000,222.500000,5442.000000
75%,263.000000,296.750000,292.250000,181.250000,209.750000,203.500000,259.000000,460.750000,513.750000,653.000000,640.250000,665.500000,649.500000,787.250000,560.000000,578.000000,625.250000,630.750000,539.000000,567.250000,745.750000,791.250000,664.750000,669.000000,740.750000,770.250000,811.500000,940.500000,956.250000,907.250000,955.000000,824.500000,790.000000,826.500000,22795.500000
max,22045.000000,24796.000000,20620.000000,10015.000000,10170.000000,9564.000000,9470.000000,21337.000000,27359.000000,23795.000000,31668.000000,23380.000000,34123.000000,33720.000000,39231.000000,30145.000000,29322.000000,22965.000000,21049.000000,30069.000000,35529.000000,36434.000000,31961.000000,36439.000000,36619.000000,42584.000000,33848.000000,28742.000000,30037.000000,29622.000000,38617.000000,36765.000000,34315.000000,34129.000000,691904.000000

In [ ]:
df_can.head(2)

,Belize,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1,Total
0,Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205,238,290,284,391,397,2852
1,Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487,5876

In [ ]:
# describe kolom-kolom string/object
df_can[['Belize','Latin America and the Caribbean','Central America','Developing regions']].describe()

,Belize,Latin America and the Caribbean,Central America,Developing regions
count,176,176,176,176
unique,176,6,22,2
top,Benin,Africa,Eastern Africa,Developing regions
freq,1,52,17,134

In [ ]:
df_can.Belize.value_counts()

Benin                         1
Bhutan                        1
Palau                         1
Panama                        1
Papua New Guinea              1
                             ..
India                         1
Indonesia                     1
Iran (Islamic Republic of)    1
Iraq                          1
Zimbabwe                      1
Name: Belize, Length: 176, dtype: int64

# Indexing dan Slicing

In [ ]:
# indexing
df_can['Belize']

0                                 Benin
1                                Bhutan
2      Bolivia (Plurinational State of)
3                Bosnia and Herzegovina
4                              Botswana
                     ...
171                            Viet Nam
172                      Western Sahara
173                               Yemen
174                              Zambia
175                            Zimbabwe
Name: Belize, Length: 176, dtype: object

In [ ]:
df_can[['Belize','Central America']]

                               Belize     Central America
0                               Benin      Western Africa
1                              Bhutan       Southern Asia
2    Bolivia (Plurinational State of)       South America
3              Bosnia and Herzegovina     Southern Europe
4                            Botswana     Southern Africa
..                                ...                 ...
171                          Viet Nam  South-Eastern Asia
172                    Western Sahara     Northern Africa
173                             Yemen        Western Asia
174                            Zambia      Eastern Africa
175                          Zimbabwe      Eastern Africa

[176 rows x 2 columns]

# Loc Iloc

In [ ]:
df_can.loc[1,'Belize']

'Bhutan'

In [ ]:
df_can.head(2)

,Belize,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1,Total
0,Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205,238,290,284,391,397,2852
1,Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487,5876

In [ ]:
df_can.loc[0:5,'Belize':48]

,Belize,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48
0,Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205
1,Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36
2,Bolivia (Plurinational State of),Latin America and the Caribbean,South America,Developing regions,44,52,42,49,38,44,79,165,63,68,71,214,247,180,75,61,96,43,33,42,33,72,57,59,85,134,139,107,143
3,Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,0,0,0,0,0,0,258,2095,2090,3007,2599,2214,2789,2737,854,801,433,267,188,211,217,209,182
4,Botswana,Africa,Southern Africa,Developing regions,10,1,3,3,7,4,2,3,8,8,2,2,4,4,0,2,3,2,0,2,3,2,4,4,9,7,11,8,28
5,Brazil,Latin America and the Caribbean,South America,Developing regions,211,220,192,139,145,130,205,244,394,650,650,877,1066,866,566,572,586,591,531,626,845,847,745,839,917,969,1181,1746,2138

In [ ]:
df_can.iloc[0:5,0:7]

,Belize,Latin America and the Caribbean,Central America,Developing regions,16,27,13
0,Benin,Africa,Western Africa,Developing regions,2,5,4
1,Bhutan,Asia,Southern Asia,Developing regions,0,0,0
2,Bolivia (Plurinational State of),Latin America and the Caribbean,South America,Developing regions,44,52,42
3,Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0
4,Botswana,Africa,Southern Africa,Developing regions,10,1,3

# Set Index

In [ ]:
df_can.head()

,Belize,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1,Total
0,Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205,238,290,284,391,397,2852
1,Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487,5876
2,Bolivia (Plurinational State of),Latin America and the Caribbean,South America,Developing regions,44,52,42,49,38,44,79,165,63,68,71,214,247,180,75,61,96,43,33,42,33,72,57,59,85,134,139,107,143,214,180,86,83,107,3205
3,Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,0,0,0,0,0,0,258,2095,2090,3007,2599,2214,2789,2737,854,801,433,267,188,211,217,209,182,156,168,140,121,119,21855
4,Botswana,Africa,Southern Africa,Developing regions,10,1,3,3,7,4,2,3,8,8,2,2,4,4,0,2,3,2,0,2,3,2,4,4,9,7,11,8,28,15,42,53,64,76,396

In [ ]:
df_can.set_index('Belize',inplace=True)
df_can.head(2)

,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1,Total
Belize,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205,238,290,284,391,397,2852
Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487,5876

In [ ]:
df_can.index.name=None
df_can.head()

,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1,Total
Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205,238,290,284,391,397,2852
Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487,5876
Bolivia (Plurinational State of),Latin America and the Caribbean,South America,Developing regions,44,52,42,49,38,44,79,165,63,68,71,214,247,180,75,61,96,43,33,42,33,72,57,59,85,134,139,107,143,214,180,86,83,107,3205
Bosnia and Herzegovina,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,0,0,0,0,0,0,258,2095,2090,3007,2599,2214,2789,2737,854,801,433,267,188,211,217,209,182,156,168,140,121,119,21855
Botswana,Africa,Southern Africa,Developing regions,10,1,3,3,7,4,2,3,8,8,2,2,4,4,0,2,3,2,0,2,3,2,4,4,9,7,11,8,28,15,42,53,64,76,396

In [ ]:
df_can.loc['Japan']

Latin America and the Caribbean                 Asia
Central America                         Eastern Asia
Developing regions                 Developed regions
16                                               701
27                                               756
13                                               598
21                                               309
37                                               246
26                                               198
25                                               248
23                                               422
53                                               324
33                                               494
38                                               379
41                                               506
27.1                                             605
37.1                                             907
41.1                                             956
43                                               826
27.2                                             994
33.1                                             924
20                                               897
37.2                                            1083
28                                              1010
24                                              1092
35                                               806
16.1                                             817
25.1                                             973
37.3                                            1067
24.1                                            1212
28.1                                            1250
48                                              1284
38.1                                            1194
39                                              1168
36                                              1265
34                                              1214
53.1                                             982
Total                                          27707
Name: Japan, dtype: object

In [ ]:
df_can[df_can.index=='Japan'].T.squeeze() # squeeze berfungsi merubah dataframe menjadi series

Latin America and the Caribbean                 Asia
Central America                         Eastern Asia
Developing regions                 Developed regions
16                                               701
27                                               756
13                                               598
21                                               309
37                                               246
26                                               198
25                                               248
23                                               422
53                                               324
33                                               494
38                                               379
41                                               506
27.1                                             605
37.1                                             907
41.1                                             956
43                                               826
27.2                                             994
33.1                                             924
20                                               897
37.2                                            1083
28                                              1010
24                                              1092
35                                               806
16.1                                             817
25.1                                             973
37.3                                            1067
24.1                                            1212
28.1                                            1250
48                                              1284
38.1                                            1194
39                                              1168
36                                              1265
34                                              1214
53.1                                             982
Total                                          27707
Name: Japan, dtype: object

In [ ]:
df_can.loc['Benin':'Bhutan','Latin America and the Caribbean':48]

,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48
Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205
Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36

In [ ]:
df_can.loc['Benin':'Bhutan',['Latin America and the Caribbean','Central America','Developing regions',48]]

,Latin America and the Caribbean,Central America,Developing regions,48
Benin,Africa,Western Africa,Developing regions,205
Bhutan,Asia,Southern Asia,Developing regions,36

In [ ]:
df_can.columns

Index(['Latin America and the Caribbean',                 'Central America',
                    'Developing regions',                                16,
                                      27,                                13,
                                      21,                                37,
                                      26,                                25,
                                      23,                                53,
                                      33,                                38,
                                      41,                            '27.1',
                                  '37.1',                            '41.1',
                                      43,                            '27.2',
                                  '33.1',                                20,
                                  '37.2',                                28,
                                      24,                                35,
                                  '16.1',                            '25.1',
                                  '37.3',                            '24.1',
                                  '28.1',                                48,
                                  '38.1',                                39,
                                      36,                                34,
                                  '53.1',                           'Total'],
      dtype='object')

In [ ]:
list(map(str,df_can.columns))

['Latin America and the Caribbean',
 'Central America',
 'Developing regions',
 '16',
 '27',
 '13',
 '21',
 '37',
 '26',
 '25',
 '23',
 '53',
 '33',
 '38',
 '41',
 '27.1',
 '37.1',
 '41.1',
 '43',
 '27.2',
 '33.1',
 '20',
 '37.2',
 '28',
 '24',
 '35',
 '16.1',
 '25.1',
 '37.3',
 '24.1',
 '28.1',
 '48',
 '38.1',
 '39',
 '36',
 '34',
 '53.1',
 'Total']

In [ ]:
df_can.columns = list(map(str,df_can.columns))
df_can.columns

Index(['Latin America and the Caribbean', 'Central America',
       'Developing regions', '16', '27', '13', '21', '37', '26', '25', '23',
       '53', '33', '38', '41', '27.1', '37.1', '41.1', '43', '27.2', '33.1',
       '20', '37.2', '28', '24', '35', '16.1', '25.1', '37.3', '24.1', '28.1',
       '48', '38.1', '39', '36', '34', '53.1', 'Total'],
      dtype='object')

In [ ]:
df_can.columns = df_can.columns.astype(str)
df_can.columns

Index(['Latin America and the Caribbean', 'Central America',
       'Developing regions', '16', '27', '13', '21', '37', '26', '25', '23',
       '53', '33', '38', '41', '27.1', '37.1', '41.1', '43', '27.2', '33.1',
       '20', '37.2', '28', '24', '35', '16.1', '25.1', '37.3', '24.1', '28.1',
       '48', '38.1', '39', '36', '34', '53.1', 'Total'],
      dtype='object')

In [ ]:
df_can.head(2)

,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1,Total
Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205,238,290,284,391,397,2852
Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487,5876

In [ ]:
df_can.loc['Benin':'Bhutan','Latin America and the Caribbean':'Developing regions']

       Latin America and the Caribbean Central America  Developing regions
Benin                           Africa  Western Africa  Developing regions
Bhutan                            Asia   Southern Asia  Developing regions

In [ ]:
# useful for plotting
list(range(16,48))

[16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47]

In [ ]:
list(map(str,range(16,48)))

['16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47']

In [ ]:
df_can.head(2)

,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1,Total
Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205,238,290,284,391,397,2852
Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487,5876

# Filtering

In [ ]:
df_can[(df_can['Latin America and the Caribbean']=='Africa')&(df_can['Central America']=='Southern Asia')]

Empty DataFrame
Columns: [Latin America and the Caribbean, Central America, Developing regions, 16, 27, 13, 21, 37, 26, 25, 23, 53, 33, 38, 41, 27.1, 37.1, 41.1, 43, 27.2, 33.1, 20, 37.2, 28, 24, 35, 16.1, 25.1, 37.3, 24.1, 28.1, 48, 38.1, 39, 36, 34, 53.1, Total]
Index: []

# Matplotlib

In [ ]:
import matplotlib.pyplot as plt
import matplotlib as ml

# magic function
%matplotlib inline

In [ ]:
print('Matplotlib version: ',ml.__version__)

Matplotlib version:  3.7.1

In [ ]:
# mengatur style matplotlib
print(plt.style.available)
ml.style.use(['ggplot'])

['Solarize_Light2', '_classic_test_patch', '_mpl-gallery', '_mpl-gallery-nogrid', 'bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn-v0_8', 'seaborn-v0_8-bright', 'seaborn-v0_8-colorblind', 'seaborn-v0_8-dark', 'seaborn-v0_8-dark-palette', 'seaborn-v0_8-darkgrid', 'seaborn-v0_8-deep', 'seaborn-v0_8-muted', 'seaborn-v0_8-notebook', 'seaborn-v0_8-paper', 'seaborn-v0_8-pastel', 'seaborn-v0_8-poster', 'seaborn-v0_8-talk', 'seaborn-v0_8-ticks', 'seaborn-v0_8-white', 'seaborn-v0_8-whitegrid', 'tableau-colorblind10']

# Case Study

## Pada tahun 2010, Haiti mengalami bencana gempa bumi berkekuatan 7,0 Gempa tersebut menyebabkan kerusakan yang luas dan korban jiwa dan sekitar tiga juta orang terkena dampak bencana alam ini. Sebagai bagian dari upaya kemanusiaan Kanada, pemerintah Kanada meningkatkan upayanya dalam menerima pengungsi dari Haiti. Kita dapat dengan cepat memvisualisasikan upaya ini menggunakan Line Plot

In [ ]:
years = list(map(str, range(16,43)))
years

['16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42']

In [ ]:
df_can.head(2)

,Latin America and the Caribbean,Central America,Developing regions,16,27,13,21,37,26,25,23,53,33,38,41,27.1,37.1,41.1,43,27.2,33.1,20,37.2,28,24,35,16.1,25.1,37.3,24.1,28.1,48,38.1,39,36,34,53.1,Total
Benin,Africa,Western Africa,Developing regions,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205,238,290,284,391,397,2852
Bhutan,Asia,Southern Asia,Developing regions,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487,5876

In [ ]:
haiti.index

Index(['Latin America and the Caribbean', 'Central America',
       'Developing regions', '16', '27', '13', '21', '37', '26', '25', '23',
       '53', '33', '38', '41', '27.1', '37.1', '41.1', '43', '27.2', '33.1',
       '20', '37.2', '28', '24', '35', '16.1', '25.1', '37.3', '24.1', '28.1',
       '48', '38.1', '39', '36', '34', '53.1', 'Total'],
      dtype='object')

In [ ]:
haiti.shape

(38,)

# Use Case 2 : Compare Immigration from india and China from 1980 to 2013

In [ ]:
years

['16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42']